Fixed bug when used "\\" at the end of string
kawamuray/jsonpath pull request #1
Opened 2020-12-02 14:41 UTC by vsile

```
{
  "metrics": [
    {
        "path": "dpc\\root\\GRs\\PK\\gr047_mirror",
        "value": "0"
    },
    {
        "path": "dpc\\root\\GR\\PK\\",
        "value": "1"
    },
    {
        "path": "dpc\\root\\GRs\\PK\\gr048_mirror",
        "value": "1"
    }
  ]
}
```
The next command returns an error because backslash before quote.
```
$ ./jsonpath --file=test_export.json --path='$.metrics[*].path+' --keys
```
In this case backslash is escaped and there is no syntax error.
So we need to consider the character before previous.

2020-12-08 02:30 UTC, kawamuray commented
Thanks for the patch :)
Curious what happens if the input string is like `"dpc\\root\\GR\\PK\\\""`. In this case  the parsed string is supposed to be `dpc\root\GR\PK\"` but the patched code produces a string without trailing dquote I think?

2020-12-08 10:12 UTC, vsile commented
You're right.
Also I should note that even in previous original code we can't use escaped double quote before closing double quote
```
{
  "metrics": [
    {
        "path": "dpc\\root\\GRs\\PK\\gr047_mirror",
        "value": "0"
    },
    {
        "path": "\"Some text\"",
        "value": "1"
    },
    {
        "path": "dpc\\root\\GRs\\PK\\gr048_mirror",
        "value": "1"
    }
  ]
}
```
Run jsonpath and get error
```
$ ./jsonpath --file=test_export.json --path='$.metrics[*].path+' --keys
"metrics"	0	"path"	"dpc\\root\\GRs\\PK\\gr047_mirror"
Unexpected character after json value token: U+0076 'v' at byte index 155
```

In the current patch we have solve this issue and take in consideration the next cases:
```"path": "dpc\\root\\GR\\PK\\"```
```"path": "dpc\\root\\GR\\PK\\\""```

2020-12-11 06:22 UTC, kawamuray commented
Thanks for the follow-up. 

I think this implementation still fails for input like `PK\\\\"`. In this case, when `curByte` reaches to the last dquote, all of `previous`, `byteBeforePrevious` and `secondByteBeforePrevious` points to a backslash so it doesn't break out of the loop, but the intention of the input string is like 1st backslash escapes the 2nd, and 3rd backslash escapes the 4th, so the dquote isn't escaped.

I'm not fully sure if I understand the original implementation correctly, since this repository was a fork of another original (but the original repository has gone so now this repo looks like the original), but I think correct backslash escaping needs to be implemented by "looking forward" rather than "looking back"? something like below:

```
for {
  curByte = ...
  l.lexeme.WriteByte(curByte)

  if curByte == '\\' {
      // look forward
      next = bufInput.ReadByte();
      if next is not null {
          WriteByte(next);
      }
  } else if curByte == '"' {
     // this dquote is not escaped
     break;
  }
}
```

2020-12-11 06:23 UTC, kawamuray requested changes
Please see the above comment.

2020-12-11 13:28 UTC, vsile commented
Now we count the backslashes before double quote.
If the number of backslashes before double quote is even then break loop.
`"`, `\\"`, `\\\\"`, etc
If odd then it means that double quote were escaped.
`\"`, `\\\"`, `\\\\\"`, etc

2020-12-11 16:01 UTC, kawamuray approved these changes
Ok, I think that approach works too. LGTM, thanks 👍

2020-12-11 16:02 UTC, merged